apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: http
      protocol: TCP
      port: 21
      targetPort: 21
    - name: pasv
      port: 40000
      targetPort: 40000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 40000
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps -o comm | grep 'telegraf' && ps -o comm | grep 'vsftpd'
          initialDelaySeconds: 30
          periodSeconds: 10