apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  serviceName: influxdb
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: telegraf
      automountServiceAccountToken: true
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
          name: influxdb
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - ps -o comm | grep 'telegraf' && ps -o comm | grep 'influxd'
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-persistent-storage
        persistentVolumeClaim:
          claimName: influxdb-pvc
